### ISSUE TITLE
graphviz

### ISSUE THREAD

**Issue by flytape8490** [notepad-plus-plus/userDefinedLanguages#24] opened 2020-03-23 02:59 UTC
The graphviz UDL does not point to an xml, instead it points to an html document

**Comment by fatgonzo** [comment] 2020-03-27 19:31
Ran into this as well while trying to grab the UDL for Tinyfugue. It appears to apply to the following files:

UDLs/TinyFugue_byYrwin.xml
UDLs/StringTemplate3_byAnnaCzerwiec.xml
UDLs/MSC-Patran_by-onurarifyasa.xml
UDLs/MSC-Nastran_by-onurarifyasa.xml
UDLs/HQL_byAkeelUdar.xml
UDLs/GraphViz_by-signmotion.xml
UDLs/AuditCommandLanguage-ACL_byJChen.xml
UDLs/AsteriskExtensionLanguage-AEL_by-eyzel.xml

The content seems to be the download page served by Sourceforge, and the few I checked out of those appear to have their original UDL file hosted there, separately from the original location of the old Notepad++ UDL archive which was mentioned in one of the closed issues. Maybe grabbing the UDLs from Sourceforge triggered some sort of finite crawler trap of sorts due to the dynamic nature of the download page, either when building the original archive or moving it here. 

Anyways, thought I'd leave this here rather than open a new issue that is actually a duplicate of this one.

**Comment by chcg** [comment] 2020-03-28 16:14
The download link github content as e.g for UDL is not the path to the html site at https://github.com/signmotion/graphviz-syntax-highlighting/blob/master/graphviz-notepad-udl.xml, but
, but https://raw.githubusercontent.com/signmotion/graphviz-syntax-highlighting/master/graphviz-notepad-udl.xml

**Comment by chcg** [comment] 2020-03-28 17:02
Some fixes, see

Additional findings to the one above:
Html 404 Download failure:
UDLs\EGL-EnterpriseGenerationLanguage_byKoen.xml

Probably Zip files:
UDLs\Alloy_by-lausdahl.xml
UDLs\jQuery_byJamesAllardice.xml

**Comment by pryrt** [comment] 2020-04-08 21:53
#25 closed the issue

**Closed by pryrt** 2020-04-08 21:53 UTC
Labels: bug
